name: Backend CI/CD

on:
push:
    branches:
    - main
    - develop
    - sprint1
jobs:
build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
    uses: actions/checkout@v2

    - name: Set up Python
    uses: actions/setup-python@v2
    with:
        python-version: '3.9'

    - name: Install dependencies
    run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r backend/requirements.txt

    - name: Run Tests
    run: |
        source venv/bin/activate
        # Add commands to run tests
        echo "Tests not set up"

    - name: Deploy to Server
    uses: easingthemes/ssh-deploy@v2.1.5
    with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        remote-user: your_server_user
        server-ip: your_server_ip
        remote-path: /path/to/edutrack/backend
        local-path: backend/